# 版权 @2022 凹语言 作者。保留所有权利。

name: Close PRs

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        # Optional. Post a issue comment just before closing a pull request.
        comment: "这里是镜像仓库, 不接受 PR, 请移步 https://gitcode.com/wa-lang/wa"
